package com.testmgmt.service;

import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Service to convert various file types to PDF format for test evidence downloads.
 * Supports: Images (PNG, JPG, GIF, BMP), Text files, and existing PDFs (pass-through).
 */
@Service
@Slf4j
public class PdfConversionService {

    private static final String[] IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff"};
    private static final String[] TEXT_EXTENSIONS = {".txt", ".log", ".json", ".xml", ".csv", ".html", ".md"};

    /**
     * Convert a file to PDF format.
     * @param sourcePath Path to the original file
     * @param originalFileName Original file name for display
     * @return byte array of the PDF content
     */
    public byte[] convertToPdf(Path sourcePath, String originalFileName) throws IOException {
        String fileName = originalFileName.toLowerCase();
        
        // If already PDF, return as-is
        if (fileName.endsWith(".pdf")) {
            return Files.readAllBytes(sourcePath);
        }

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        
        try (PdfWriter writer = new PdfWriter(outputStream);
             PdfDocument pdfDoc = new PdfDocument(writer);
             Document document = new Document(pdfDoc)) {

            // Add header with file info
            addHeader(document, originalFileName);

            // Convert based on file type
            if (isImageFile(fileName)) {
                convertImageToPdf(document, sourcePath);
            } else if (isTextFile(fileName)) {
                convertTextToPdf(document, sourcePath);
            } else {
                // For unsupported types, create a placeholder PDF
                convertUnsupportedToPdf(document, sourcePath, originalFileName);
            }

            // Add footer
            addFooter(document);
        }

        return outputStream.toByteArray();
    }

    private void addHeader(Document document, String originalFileName) {
        Paragraph header = new Paragraph("Test Evidence Document")
                .setFontSize(18)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER);
        document.add(header);

        Paragraph subHeader = new Paragraph("Original File: " + originalFileName)
                .setFontSize(10)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER);
        document.add(subHeader);

        Paragraph timestamp = new Paragraph("Downloaded: " + 
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(timestamp);

        document.add(new Paragraph("\n"));
    }

    private void addFooter(Document document) {
        document.add(new Paragraph("\n"));
        Paragraph footer = new Paragraph("Generated by Test Genii AI Test Management System")
                .setFontSize(8)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER);
        document.add(footer);
    }

    private void convertImageToPdf(Document document, Path imagePath) throws IOException {
        try {
            byte[] imageBytes = Files.readAllBytes(imagePath);
            Image image = new Image(ImageDataFactory.create(imageBytes));
            
            // Scale image to fit page width while maintaining aspect ratio
            float pageWidth = document.getPdfDocument().getDefaultPageSize().getWidth() - 100;
            if (image.getImageWidth() > pageWidth) {
                image.scaleToFit(pageWidth, Float.MAX_VALUE);
            }
            
            image.setHorizontalAlignment(com.itextpdf.layout.properties.HorizontalAlignment.CENTER);
            document.add(image);
            
            log.debug("Converted image {} to PDF", imagePath);
        } catch (Exception e) {
            log.error("Failed to convert image to PDF: {}", e.getMessage());
            document.add(new Paragraph("Error: Could not embed image. " + e.getMessage())
                    .setFontColor(com.itextpdf.kernel.colors.ColorConstants.RED));
        }
    }

    private void convertTextToPdf(Document document, Path textPath) throws IOException {
        try {
            String content = Files.readString(textPath);
            
            // Limit content length to prevent huge PDFs
            if (content.length() > 50000) {
                content = content.substring(0, 50000) + "\n\n... [Content truncated - file too large]";
            }
            
            Paragraph contentPara = new Paragraph(content)
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.LEFT);
            document.add(contentPara);
            
            log.debug("Converted text file {} to PDF", textPath);
        } catch (Exception e) {
            log.error("Failed to convert text file to PDF: {}", e.getMessage());
            document.add(new Paragraph("Error: Could not read text file. " + e.getMessage())
                    .setFontColor(com.itextpdf.kernel.colors.ColorConstants.RED));
        }
    }

    private void convertUnsupportedToPdf(Document document, Path filePath, String originalFileName) throws IOException {
        Paragraph notice = new Paragraph("File Type Notice")
                .setFontSize(14)
                .setBold();
        document.add(notice);

        String fileExtension = originalFileName.contains(".") 
                ? originalFileName.substring(originalFileName.lastIndexOf("."))
                : "unknown";

        Paragraph info = new Paragraph(
                "The original file (" + originalFileName + ") is in " + fileExtension.toUpperCase() + 
                " format which cannot be directly embedded in PDF.\n\n" +
                "File Details:\n" +
                "- Original Name: " + originalFileName + "\n" +
                "- File Size: " + Files.size(filePath) + " bytes\n" +
                "- File Type: " + fileExtension + "\n\n" +
                "Please contact the test team if you need the original file format.")
                .setFontSize(11);
        document.add(info);
        
        log.info("Created placeholder PDF for unsupported file type: {}", originalFileName);
    }

    private boolean isImageFile(String fileName) {
        for (String ext : IMAGE_EXTENSIONS) {
            if (fileName.endsWith(ext)) return true;
        }
        return false;
    }

    private boolean isTextFile(String fileName) {
        for (String ext : TEXT_EXTENSIONS) {
            if (fileName.endsWith(ext)) return true;
        }
        return false;
    }
}
